### ISSUE TITLE
Feature: Rename Projections

### ISSUE THREAD

**Issue by openfirmware** [GeoSensorWebLab/polarmap.js#1]
I received a request to rename the projections in the drop-down selection map control. They currently have these names:
- Arctic Connect: EPSG:3571
- Arctic Connect: EPSG:3572
- Arctic Connect: EPSG:3573
- Arctic Connect: EPSG:3574
- Arctic Connect: EPSG:3575
- Arctic Connect: EPSG:3576

These names are not very self-descriptive. Instead, we could use the actual name for each projection.
- [EPSG:3571 Bering Sea](http://epsg.io/3571)
- [EPSG:3572 Alaska](http://epsg.io/3572)
- [EPSG:3573 Canada](http://epsg.io/3573)
- [EPSG:3574 Atlantic](http://epsg.io/3574)
- [EPSG:3575 Europe](http://epsg.io/3575)
- [EPSG:3576 Russia](http://epsg.io/3576)

Any comments?

**Comment by liangsteve** [comment]
Looks good!  BTW, where is the comment coming from?

**Comment by openfirmware** [comment]
Bindu with the Arctic Institute asked about the names during one of our community workshops.

**Comment by liangsteve** [comment]
:+1:  Great.  Just think it's a good idea to document it in the issue tracking system here.
