### ISSUE TITLE
Track down "magic" numbers

### ISSUE THREAD

**Issue by openfirmware** [GeoSensorWebLab/polarmap.js#3]
On the LAEA tile configuration, [I am using a magic number for the projection's extent](https://github.com/GeoSensorWebLab/polarmap.js/blob/master/src/layer/tile/LAEATileLayer.js#L5):

```
var extent = 11000000 + 9036842.762 + 667;
```

I honestly don't know where all of these numbers come from. I added the 667 to get the map to "line up" markers properly as they were offset a bit from their true positions (when compared to the marker positions on an EPSG:3857 map such as OpenStreetMap). 9036842.762 is exactly the [extent for the LAEA projections 3571 – 3576](http://nsidc.org/data/atlas/laea_north_nsidc.html). But the 11 million is a mystery.

While the map appears to "work" with the tile backend, I am not sure why these numbers work and I would like to know. If it helps, [here is the configuration for the tiles on the server side](https://github.com/GeoSensorWebLab/awm-styles/blob/master/project.yaml.erb). The tiles are rendered with Mapnik and renderd/mod_tile.

I may have to set up a local installation of the tile server and PolarMap.js to test changes on both the server and client at the same time. If so, I will write up a guide on how to do that.

**Comment by timrobertson100** [comment]
I am also digging into this, and I believe it _might_ relate to the fact that while the recommended envelope for the projection is above 45 degrees, you can paint a tile to world extent with heavy distortion at the edges if you wish.  

Therefore you need to consider the world bounds, which means the circumference of the earth at the equator (approx 40 million meters).  If you add those numbers up, you get approx 20 million which correlates to 40 million when considering you have +20 and -20 million.

I have written my own data overlays, and it was this logic that I needed to apply in my [scaling AffineTransform](https://github.com/gbif/maps/blob/master/common/src/main/java/org/gbif/maps/common/projection/NorthPoleLAEAEurope.java#L69) to align .

**Comment by openfirmware** [comment]
Interesting! I recall now I had to cut all the shapefiles to exclude data below the equator, as the distortion caused glitchy rendering with Antarctica. Here is what I mean in QGIS:

<img width="763" alt="no-cut-epsg-3573" src="https://cloud.githubusercontent.com/assets/68210/15945337/272ba7a0-2e4f-11e6-9eac-9d9873f82879.png">

And with a crop:

<img width="787" alt="cut-epsg-3573" src="https://cloud.githubusercontent.com/assets/68210/15945340/2bded84e-2e4f-11e6-92ea-fdf840a0a580.png">

(Scale is 1:120,000,000, EPSG:3573 on-the-fly reprojection)

That would explain the empty space around the world at zoom level 0.

Your suggestion regarding the equator seems to be the solution, and the "9036842.762" number is just me extracting a number that isn't actually relevant.

The LAEA projections of EPSG:3571 to 3576 are all using the [WGS84 ellipsoid](http://epsg.io/3571). [The ellipsoid](https://en.wikipedia.org/wiki/World_Geodetic_System) uses an equatorial radius of 6 378 137 metres, which corresponds to a equatorial circumference of 40 075 016.686 metres. Half that is 20 037 508.343 metres. The magic number in the PolarMap.js code is 20 037 509.762 metres: very close!

Your code is similar to how Proj4Leaflet handles the resolutions. I first define the [metres per pixel in the tile layer](https://github.com/GeoSensorWebLab/polarmap.js/blob/master/src/layer/tile/LAEATileLayer.js#L25), the use those to [build the resolution zoom steps](https://github.com/GeoSensorWebLab/polarmap.js/blob/master/src/map/Map.js#L79) for a custom Map CRS on Leaflet.

Thanks for the help Tim! I will do some testing with replacing the magic number with the half-circumference and see if markers still line up properly. If so I will release a new version of PolarMap with the new number.

**Comment by timrobertson100** [comment]
Great.  40,075,016.686 is [also the number I used](https://github.com/gbif/maps/blob/master/common/src/main/java/org/gbif/maps/common/projection/AbstractTileProjection.java#L8) as I found it in Leaflet and some other GIS libs.  Good to know that it corresponds with the WGS84 equatorial radius.

**Comment by openfirmware** [comment]
I adjusted the extent and saw a tiny shift in marker placement:

![comparison](https://cloud.githubusercontent.com/assets/68210/15976990/4ebe9e34-2f13-11e6-8050-9ba97ffebee9.gif)

This is to be expected and should be a more accurate representation of the location.

**Comment by duckontheweb** [comment]
I just set these to the extents given by @openfirmware [here](https://github.com/GeoSensorWebLab/awm-styles/blob/master/project.yaml.erb) (`[-20037508, 20037508]`) without any other adjustments and it seemed to pinpoint the location accurately. I may be misunderstanding things, but I don't think that the only thing that the `origin` property in proj4leaflet needs to know is where the tile origin point is, and that can come directly from the projected tile extents.

@openfirmware Are the tile extent settings the same for the other Arctic projections? If not, could you point me to the configs for those?

Thanks

**Comment by openfirmware** [comment]
The extent settings should be the same for the other projections, the only difference in configuration on the tile server (https://github.com/GeoSensorWebLab/awm-styles/blob/master/awm-styles.yaml) is that the Spatial Reference System string has a different central meridian.

**Comment by duckontheweb** [comment]
Awesome, thanks. After digging into this a bit more, it looks like that origin/extent value [comes from the major axis after all](https://github.com/GeoSensorWebLab/polarmap.js/blob/master/src/layer/tile/LAEATileLayer.js#L5-L6). Should have just followed your link in the first place... Thanks for the help.
