### ISSUE TITLE
Potential help for anyone using leaflet with polar stereographic, WMS, or ESRI map.

### ISSUE THREAD

**Issue by scaddenp** [GeoSensorWebLab/polarmap.js#7]
While not explicitly a polarjs issue (and we are using latest leaflet code), we did find bugs and fixes while working with antarctica EPSG:3031 which are probably highly relevant to this plugin. 

This issue is https://github.com/Leaflet/Leaflet/issues/5617

**Comment by openfirmware** [comment]
Hi!

Thanks for the info on potential problems. I haven't worked with WMS and PolarMap.js yet, so I haven't encountered that issue. PolarMap.js is still on the 0.7 branch of Leaflet as well, so there may be some changes in Leaflet 1.0 that need to be considered.

I will keep an eye out for those kinds of deformations and visual glitches in imagery layers added via Leaflet.
